trading_pairs = {
    "symbols": [
        {
            "symbol": "AVAXUSDT",
            "enabled": True,
            "long_enabled": True,
            "short_enabled": True,
            "long_order_limit": 20,
            "short_order_limit": 20,
            "long_margin_limit": None,  # None = no limit, or absolute price like 30.0
            "short_margin_limit": None,  # None = no limit, or absolute price like 10.0
            "position_size": 1,
            "order_threshold_percent": 1.0,
            "profit_threshold_percent": 1.0,
            "trailing_stop_callback_rate": 0.5,
            "forward_order_block_percent": 1,
            "backward_order_block_percent": 1,
            "order_type": "MARKET",
            "leverage": 5,
            "margin_asset": "USDT",
            "price_precision": 4,
            "quantity_precision": 0
        },
        {
            "symbol": "SOLUSDT",
            "enabled": True,
            "long_enabled": True,
            "short_enabled": True,
            "long_order_limit": 20,
            "short_order_limit": 20,
            "long_margin_limit": None,
            "short_margin_limit": None,
            "position_size": 1,
            "order_threshold_percent": 1.0,
            "profit_threshold_percent": 1.0,
            "trailing_stop_callback_rate": 0.5,
            "forward_order_block_percent": 1,
            "backward_order_block_percent": 1,
            "order_type": "MARKET",
            "leverage": 5,
            "margin_asset": "USDT",
            "price_precision": 4,
            "quantity_precision": 0
        },
        {
            "symbol": "NEARUSDT",
            "enabled": True,
            "long_enabled": True,
            "short_enabled": True,
            "long_order_limit": 20,
            "short_order_limit": 20,
            "long_margin_limit": None,
            "short_margin_limit": None,
            "position_size": 8,
            "order_threshold_percent": 1.0,
            "profit_threshold_percent": 1.0,
            "trailing_stop_callback_rate": 0.5,
            "forward_order_block_percent": 1,
            "backward_order_block_percent": 1,
            "order_type": "MARKET",
            "leverage": 5,
            "margin_asset": "USDT",
            "price_precision": 4,
            "quantity_precision": 0
        },
        {
            "symbol": "SUIUSDT",
            "enabled": True,
            "long_enabled": True,
            "short_enabled": True,
            "long_order_limit": 20,
            "short_order_limit": 20,
            "long_margin_limit": None,
            "short_margin_limit": None,
            "position_size": 8,
            "order_threshold_percent": 1.0,
            "profit_threshold_percent": 1.0,
            "trailing_stop_callback_rate": 0.5,
            "forward_order_block_percent": 1,
            "backward_order_block_percent": 1,
            "order_type": "MARKET",
            "leverage": 5,
            "margin_asset": "USDT",
            "price_precision": 6,
            "quantity_precision": 1
        },
        {
            "symbol": "ETHUSDT",
            "enabled": True,
            "long_enabled": True,
            "short_enabled": True,
            "long_order_limit": 20,
            "short_order_limit": 20,
            "long_margin_limit": None,
            "short_margin_limit": None,
            "position_size": 0.01,
            "order_threshold_percent": 1.0,
            "profit_threshold_percent": 1.0,
            "trailing_stop_callback_rate": 0.5,
            "forward_order_block_percent": 1,
            "backward_order_block_percent": 1,
            "order_type": "MARKET",
            "leverage": 5,
            "margin_asset": "USDT",
            "price_precision": 2,
            "quantity_precision": 3
        }
    ],
}
