trading_pairs = {
    "symbols": [
        {
            "symbol": "AVAXUSDT",
            "enabled": True,
            "long_enabled": True,
            "short_enabled": True,
            "long_order_limit": 20,
            "short_order_limit": 20,
            "long_margin_limit": None,
            "short_margin_limit": 20,
            "position_size": 1,
            "order_threshold_percent": 1.0,
            "profit_threshold_percent": 1.0,
            "trailing_stop_callback_rate": 0.3,
            "stop_loss_percent": None,
            "forward_order_block_percent": 1,
            "backward_order_block_percent": 1,
            "order_type": "MARKET",
            "leverage": 5,
            "margin_asset": "USDT",
            "price_precision": 4,
            "quantity_precision": 0
        },
        {
            "symbol": "SUIUSDT",
            "enabled": True,
            "long_enabled": True,
            "short_enabled": True,
            "long_order_limit": 20,
            "short_order_limit": 20,
            "long_margin_limit": None,
            "short_margin_limit": 2.5,
            "position_size": 10,
            "order_threshold_percent": 1.0,
            "profit_threshold_percent": 1.0,
            "trailing_stop_callback_rate": 0.3,
            "stop_loss_percent": None,
            "forward_order_block_percent": 1,
            "backward_order_block_percent": 1,
            "order_type": "MARKET",
            "leverage": 5,
            "margin_asset": "USDT",
            "price_precision": 6,
            "quantity_precision": 1
        }
        # {
        #     "symbol": "MINAUSDT",
        #     "enabled": True,
        #     "long_enabled": True,
        #     "short_enabled": True,
        #     "long_order_limit": 1,
        #     "short_order_limit": 2,
        #     "long_margin_limit": None,
        #     "short_margin_limit": None,
        #     "position_size": 120,
        #     "order_threshold_percent": 3,
        #     "profit_threshold_percent": 3,
        #     "trailing_stop_callback_rate": 1,
        #     "stop_loss_percent": 20,
        #     "forward_order_block_percent": 3,
        #     "backward_order_block_percent": 3,
        #     "order_type": "MARKET",
        #     "leverage": 5,
        #     "margin_asset": "USDT",
        #     "price_precision": 7,
        #     "quantity_precision": 0
        # }
        # {
        #     "symbol": "ZENUSDT",
        #     "enabled": True,
        #     "long_enabled": True,
        #     "short_enabled": True,
        #     "long_order_limit": 20,
        #     "short_order_limit": 20,
        #     "long_margin_limit": None,
        #     "short_margin_limit": None,
        #     "position_size": 1,
        #     "order_threshold_percent": 2,
        #     "profit_threshold_percent": 3,
        #     "trailing_stop_callback_rate": 1,
        #     "stop_loss_percent": 20,
        #     "forward_order_block_percent": 3,
        #     "backward_order_block_percent": 3,
        #     "order_type": "MARKET",
        #     "leverage": 5,
        #     "margin_asset": "USDT",
        #     "price_precision": 3,
        #     "quantity_precision": 1
        # }
    ],
}
